sonar.projectKey=tech-challenge-1
sonar.projectName=Tech Challenge 1
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests
sonar.sourceEncoding=UTF-8

# Coverage gerado pelo PHPUnit em formato Clover
sonar.php.coverage.reportPaths=coverage.xml

# Evita escanear dependencias e artefatos
sonar.exclusions=vendor/**,storage/**,bootstrap/cache/**

