name: Build and Publish Docker image (GHCR)

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Laravel CI"]
    types: [completed]
    branches: ["main", "development"]

permissions:
  actions: write
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: edunsantos/tech-challenge-application

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            type=raw,value=latest

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Dispatch deployment to Kubernetes repo
        if: github.event_name != 'pull_request'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.K8S_REPO_TOKEN }}
          repository: edunsantos/tech-challenge-kubernetes
          event-type: deploy-eks
          client-payload: |
            {
              "image": "ghcr.io/edunsantos/tech-challenge-application:latest",
              "tag": "latest",
              "sha": "${{ github.sha }}"
            }