name: Laravel CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o ambiente PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, xml, ctype, iconv, mysql, bcmath, pdo_sqlite, sqlite3
        coverage: none

    - name: Instalar dependências do Composer
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Executar os Testes Unitários
      env:
        APP_ENV: testing
        APP_KEY: base64:tExTeS84Y2hhdmVfZmFrZV9wYXJhX29fY2lfZ2l0aHViCg==
        DB_CONNECTION: sqlite
        DB_DATABASE: ':memory:'
      run: php artisan test --env=testing
